### ISSUE TITLE
Source problems

### ISSUE THREAD

**Issue by eucode** [MManoah/league-profile-tool#25]
**TERMINAL LOG**
```
√ Checking your system
It looks like you are missing some dependencies you need to get Electron running.
Make sure you have git installed and Node.js version >= 10.0.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! league-profile-tool@2.0.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the league-profile-tool@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-12-07T22_30_41_537Z-debug.log
```

**DEBUG LOG**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle league-profile-tool@2.0.0~prestart: league-profile-tool@2.0.0
6 info lifecycle league-profile-tool@2.0.0~start: league-profile-tool@2.0.0
7 verbose lifecycle league-profile-tool@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle league-profile-tool@2.0.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Admin\Desktop\league-profile-tool-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;D:\Program Files\nodejs\;C:\Program Files\OpenJDK\openjdk-8u262-b10\bin;C:\Users\Admin\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\dotnet\;C:\Users\Admin\AppData\Local\Programs\Python\Python38;C:\Users\Admin\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;;D:\Programmi\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\npm;C:\Users\Admin\.dotnet\tools
9 verbose lifecycle league-profile-tool@2.0.0~start: CWD: C:\Users\Admin\Desktop\league-profile-tool-master
10 silly lifecycle league-profile-tool@2.0.0~start: Args: [ '/d /s /c', 'electron-forge start' ]
11 silly lifecycle league-profile-tool@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle league-profile-tool@2.0.0~start: Failed to exec start script
13 verbose stack Error: league-profile-tool@2.0.0 start: `electron-forge start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid league-profile-tool@2.0.0
15 verbose cwd C:\Users\Admin\Desktop\league-profile-tool-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.13.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error league-profile-tool@2.0.0 start: `electron-forge start`
22 error Exit status 1
23 error Failed at the league-profile-tool@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xadamxk** [comment]
Just to cover all bases, have you verified that the `electron-forge` cli package is in your node_modules folder?

If it is, try purging your node modules and run `npm install` again. Let me know how it goes.

**Comment by MManoah** [comment]
> Just to cover all bases, have you verified that the `electron-forge` cli package is in your node_modules folder?
> 
> If it is, try purging your node modules and run `npm install` again. Let me know how it goes.

Try this. Also make sure you have git.
